### ISSUE TITLE
Welcome to the club!

### ISSUE THREAD

**Issue by ericclemmons** [markdalgleish/redial#1]
This is, IMO, how isomorphic apps should work (no more fat controllers), so it's nice to see more visibility on this approach!
- https://github.com/ericclemmons/react-resolver
- https://github.com/RickWong/react-transmit
- https://github.com/elierotenberg/react-nexus

:tada: :balloon: :cake: :clap:

**Comment by markdalgleish** [comment]
I only just saw this issue. Thank you! I really appreciate the encouragement :smile: 

Awesome work on react-resolver, too :tada:

**Comment by ericclemmons** [comment]
I think this library covers the use-cases of React Resolver, so I haven't felt the need to update it.

Plus, as you've probably noticed, Redux makes it much easier to do a full async render on the server.

Well done my friend :)
