### ISSUE TITLE
Error with require.ensure

### ISSUE THREAD

**Issue by luandro** [markdalgleish/redial#4]
I've been using RR's [Dynamic Routing](https://github.com/rackt/react-router/blob/latest/docs/guides/advanced/DynamicRouting.md) technique that uses `require.ensure`. When doing that I get `TypeError: Cannot read property 'fetchers' of undefined`, since it's not what [makeGetter](https://github.com/markdalgleish/react-fetcher/blob/master/src/makeGetter.js) is expecting:

```
module.exports = {
    path: '/',
    getComponent(location, cb) {
        require.ensure([], (require) => {
          cb(null, require('./containers/HomeContainer'))
        })
    }
}
```

I haven't given this much thought, just throwing it out there but it does make sense to do a prefetch on "gradual matched" routes, right?

**Comment by markdalgleish** [comment]
This should be fixed in v0.4.1. Please re-open if that's not the case.
