### ISSUE TITLE
How I can do sequential requests? I mean nested requests

### ISSUE THREAD

**Issue by victortomilin** [markdalgleish/redial#41]
Hi!

For example: I have made a one request and if request successfully done I should send additional request and when this request will be finished then SSR should work. How I can do that?

Thx.

**Comment by ctrlplusb** [comment]
Promise chains within a thunk action?

**Comment by victortomilin** [comment]
@ctrlplusb yep

**Comment by idangozlan** [comment]
try async waterfall

**Comment by victortomilin** [comment]
@idangozlan Thx u very much! async/await work for me in this case
