### ISSUE TITLE
Sessions on server

### ISSUE THREAD

**Issue by thomasdavis** [markdalgleish/redial#6]
Using react-fetcher to render on the server, wondering when do you pass on cookie/session information to fetcher and/or react from the request handler. (Just assume req.session is available for example)

p.s. great lib!

**Comment by markdalgleish** [comment]
On my current project that's using redial, we're currently avoiding sessions on the server to increase server performance. This will probably change eventually, but for now I don't have any concrete patterns on this.

This isn't so much an issue with the library, but a question of usage, so I'm closing it. But please, report back if you come up with a good solution, and I might start to collate some patterns in the readme for others to follow.
