### ISSUE TITLE
PR from react-redux-universal-hot-example

### ISSUE THREAD

**Issue by chungchiehlun** [markdalgleish/redial#8]
Hello , I don't know whether the question asked here is right or not . If not , please ignore it.

I just started to study [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example/pull/531) , and much part confused me. The [fork](https://github.com/jlongster/react-redux-universal-hot-example/commit/e13b93518c8c9b5524ad50f1c566ed6c480c1888?diff=unified)  replace `redux-router` with `redux-simple-router` and it worked well for me. 

I have problem [here](https://github.com/jlongster/react-redux-universal-hot-example/commit/e13b93518c8c9b5524ad50f1c566ed6c480c1888?diff=split#diff-c1f8389a4afaa1ba595a6814bcfb6a95). The implementation of `fetchData` and `fetchDataDeferred` is too complicated for me to understand. So I searched for other solution and came here finally. I studied your [pull request](https://github.com/markdalgleish/react-redux-universal-hot-example/commit/4d85d7ab9e16c9b31f57fe2fcff018ba433bbf85) but unfortunately it didn't make sense for me if I used `redux-simple-router`.

Would you please give me some tips ? Thank you a lot .

**Comment by markdalgleish** [comment]
Looks like I might need to patch this since this issue has been raised a few times.

**Comment by markdalgleish** [comment]
The issue you linked to should be fixed in the latest version.

**Comment by chungchiehlun** [comment]
Thank you. :)
